# Generated by Django 5.0 on 2023-12-26 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Brand of product')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name of category')),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firs_name', models.CharField(max_length=50, verbose_name='First name of customer')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name of customer')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone number of product')),
                ('email', models.EmailField(max_length=254, verbose_name='Email of customer')),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Producer of product')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name of product')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('photo', models.ImageField(default='/photo/2023/12/06/empty.png', upload_to='photo/%Y/%m/%d/', verbose_name='Image of product')),
                ('pre_description', models.CharField(max_length=90, verbose_name='Pre description of product')),
                ('description', models.TextField(verbose_name='Description of product')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.brand', verbose_name='Brand')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.category', verbose_name='Category')),
                ('producer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.producer', verbose_name='Producer')),
            ],
        ),
    ]
